{{- include "chart.validateExternalSecret" . }}
{{- if (include "chart.externalSecretEnabled" .) | eq "true" }}
{{- $es := .Values.externalSecret -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ $es.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    kind: {{ $es.secretStoreRef.kind | default "ClusterSecretStore" }}
    name: {{ $es.secretStoreRef.name | quote }}
  target:
    name: {{ .Release.Name }}-secret
    creationPolicy: Owner
  data:
    {{- range $es.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .remoteRef.key | quote }}
        {{- with .remoteRef.property }}
        property: {{ . | quote }}
        {{- end }}
    {{- end }}
{{- end }}
