{{- if (include "chart.isGrpc" .) | eq "true" }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ include "chart.gatewayName" . }}
      namespace: {{ include "chart.gatewayNamespace" . }}
      group: gateway.networking.k8s.io
      kind: Gateway
  hostnames:
    - {{ include "chart.corpHostname" . | quote }}
    {{- if .Values.legacyDns }}
    - {{ include "chart.legacyHostname" . | quote }}
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ .Release.Name }}
          port: {{ include "chart.containerPort" . | int }}
{{- end }}
