{{- include "chart.validatePersistence" . }}
{{- if (include "chart.persistenceEnabled" .) | eq "true" }}
{{- $p := .Values.persistence -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.persistencePvcName" . }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $p.size | quote }}
  {{- with $p.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
