trigger:
  - main

resources:
  repositories:
    - repository: templates
      type: github
      name: diegofernandes-dev/pipeline-templates
      endpoint: github-diegofernandes-dev
      ref: refs/tags/v3.0.0

extends:
  template: templates/dotnet/ci.yml@templates
  parameters:
    solution: '**/*.sln'
    applicationName: sample-api
    dotnetProject: src/Sample.Api/Sample.Api.csproj
    containerPool: 'PG-AWS-EKS'
    deployEnvironments:
      - name: develop
        containerPool: PG-AWS-EKS
        variableGroups: []
      - name: homolog
        containerPool: PG-AWS-EKS-HML
        variableGroups: []
