{{- $config := .Values.config | default (dict) -}}
{{- if (include "chart.configEffectiveEnabled" .) | eq "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := $config }}
  {{- if ne $key "enabled" }}
  {{ $key | replace "CM_" "" }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
