{{- $sa := .Values.serviceAccount | default dict }}
{{- if $sa.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $sa.name | default (printf "%s-sa" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  {{- if $sa.annotations }}
  annotations:
    {{- toYaml $sa.annotations | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ ternary $sa.automountServiceAccountToken false (hasKey $sa "automountServiceAccountToken") }}
{{- end }}
