{{- $svcPort := .Values.service.port | default 8080 }}
{{- $portName := include "chart.portName" . -}}
{{- $appProtocol := include "chart.serviceAppProtocol" . -}}
{{- if and ((include "chart.isDeployment" .) | eq "true") ((include "chart.serviceEnabled" .) | eq "true") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $svcPort }}
      targetPort: {{ $portName }}
      protocol: TCP
      name: {{ $portName }}
      {{- if $appProtocol }}
      appProtocol: {{ $appProtocol }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
