#!/usr/bin/env bash
# Resolve platform facts for an area + tier into a Helm values file (or facts YAML).
#
# Single source of truth: platform/areas/<area>.yml (parameter `platform` default).
# Consumers (helm-deploy, ci contract render, chart tests) MUST use this script
# instead of hardcoding area/tier → gateway / DNS / minReplicas maps.
#
# Usage:
#   ./scripts/resolve-platform-values.sh <area> <tier> [output.yaml]
#   ./scripts/resolve-platform-values.sh <area> <tier> --facts [output.yaml]
#
# Env:
#   PLATFORM_AREAS_DIR  Override the directory of area profiles (tests/fixtures).
#
# Prints YAML to stdout when output path is omitted.
# Exits non-zero if the area/tier is unknown or required keys are missing.
set -Eeuo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
AREAS_DIR="${PLATFORM_AREAS_DIR:-${ROOT}/platform/areas}"

AREA=""
TIER=""
MODE="values"
OUT_FILE=""

usage() {
  echo "usage: $0 <area> <tier> [--facts] [output.yaml]" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --facts)
      MODE="facts"
      shift
      ;;
    -h|--help)
      usage
      ;;
    *)
      if [[ -z "${AREA}" ]]; then
        AREA="$1"
      elif [[ -z "${TIER}" ]]; then
        TIER="$1"
      elif [[ -z "${OUT_FILE}" ]]; then
        OUT_FILE="$1"
      else
        usage
      fi
      shift
      ;;
  esac
done

if [[ -z "${AREA}" || -z "${TIER}" ]]; then
  usage
fi

for cmd in yq; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "ERROR: ${cmd} is required" >&2
    exit 1
  fi
done

PROFILE="${AREAS_DIR}/${AREA}.yml"
if [[ ! -f "${PROFILE}" ]]; then
  echo "ERROR: unknown area '${AREA}' — expected profile at ${PROFILE}" >&2
  exit 1
fi

# Extract the default object of the `platform` parameter from the area profile.
PLATFORM_JSON="$(yq -o=json -I=0 '
  .parameters[]
  | select(.name == "platform")
  | .default
' "${PROFILE}")"

if [[ -z "${PLATFORM_JSON}" || "${PLATFORM_JSON}" == "null" ]]; then
  echo "ERROR: ${PROFILE} has no parameters[].name==platform with a default" >&2
  exit 1
fi

PROFILE_AREA="$(printf '%s' "${PLATFORM_JSON}" | yq -r '.area // ""')"
if [[ -z "${PROFILE_AREA}" || "${PROFILE_AREA}" == "null" ]]; then
  echo "ERROR: ${PROFILE} platform.area is missing" >&2
  exit 1
fi
if [[ "${PROFILE_AREA}" != "${AREA}" ]]; then
  echo "ERROR: profile area '${PROFILE_AREA}' does not match requested '${AREA}' (${PROFILE})" >&2
  exit 1
fi

if [[ "$(printf '%s' "${PLATFORM_JSON}" | yq -r ".tiers | has(\"${TIER}\")")" != "true" ]]; then
  echo "ERROR: unknown tier '${TIER}' for area '${AREA}' — add it under platform.tiers in ${PROFILE}" >&2
  exit 1
fi

TIER_JSON="$(printf '%s' "${PLATFORM_JSON}" | yq -o=json -I=0 ".tiers.\"${TIER}\"")"

REQUIRED_KEYS=(
  gatewayName
  gatewayNamespace
  corpDnsZone
  defaultMinReplicas
)

MISSING=()
for key in "${REQUIRED_KEYS[@]}"; do
  val="$(printf '%s' "${TIER_JSON}" | yq -r ".\"${key}\" // \"\"")"
  if [[ -z "${val}" || "${val}" == "null" ]]; then
    MISSING+=("${key}")
  fi
done
if [[ "${#MISSING[@]}" -gt 0 ]]; then
  echo "ERROR: ${AREA}/${TIER} missing required keys: ${MISSING[*]}" >&2
  exit 1
fi

GATEWAY_NAME="$(printf '%s' "${TIER_JSON}" | yq -r '.gatewayName')"
GATEWAY_NAMESPACE="$(printf '%s' "${TIER_JSON}" | yq -r '.gatewayNamespace')"
CORP_DNS_ZONE="$(printf '%s' "${TIER_JSON}" | yq -r '.corpDnsZone')"
LEGACY_DNS_ZONE="$(printf '%s' "${TIER_JSON}" | yq -r '.legacyDnsZone // ""')"
DEFAULT_MIN_REPLICAS="$(printf '%s' "${TIER_JSON}" | yq -r '.defaultMinReplicas')"

if ! [[ "${DEFAULT_MIN_REPLICAS}" =~ ^[1-9][0-9]*$ ]]; then
  echo "ERROR: ${AREA}/${TIER}.defaultMinReplicas must be a positive integer (got '${DEFAULT_MIN_REPLICAS}')" >&2
  exit 1
fi

if [[ "${MODE}" == "facts" ]]; then
  # Full tier object + registry + area for pipeline guards (not chart schema).
  export RESOLVE_AREA="${AREA}" RESOLVE_TIER="${TIER}"
  YAML="$(printf '%s' "${PLATFORM_JSON}" | yq '
    {
      "area": strenv(RESOLVE_AREA),
      "tier": strenv(RESOLVE_TIER),
      "buildPool": .buildPool,
      "registry": .registry,
      "cluster": .tiers[strenv(RESOLVE_TIER)]
    }
  ')"
else
  # Chart-facing subset only (values.schema.json platform.* + runtime.environment).
  LEGACY_LINE=""
  if [[ -n "${LEGACY_DNS_ZONE}" && "${LEGACY_DNS_ZONE}" != "null" ]]; then
    LEGACY_LINE="  legacyDnsZone: ${LEGACY_DNS_ZONE}"
  fi
  YAML="$(cat <<EOF
# Generated by scripts/resolve-platform-values.sh — do not edit by hand.
# area: ${AREA}  tier: ${TIER}
runtime:
  environment: ${TIER}
platform:
  area: ${AREA}
  tier: ${TIER}
  gatewayName: ${GATEWAY_NAME}
  gatewayNamespace: ${GATEWAY_NAMESPACE}
  corpDnsZone: ${CORP_DNS_ZONE}
${LEGACY_LINE}
  defaultMinReplicas: ${DEFAULT_MIN_REPLICAS}
EOF
)"
  # Drop blank line left when legacyDnsZone is absent.
  YAML="$(printf '%s\n' "${YAML}" | sed '/^$/d')"
fi

if [[ -n "${OUT_FILE}" ]]; then
  printf '%s\n' "${YAML}" > "${OUT_FILE}"
else
  printf '%s\n' "${YAML}"
fi
