#!/usr/bin/env bash
# Resolve a runtime profile's chart: section into a Helm values file.
#
# Single source of truth: platform/runtimes/<runtime>.yml
#
# Usage:
#   ./scripts/resolve-runtime-values.sh <runtime> [output.yaml]
#
# Env:
#   PLATFORM_RUNTIMES_DIR  Override the directory of runtime profiles (tests/fixtures).
#
# Prints YAML to stdout when output path is omitted.
set -Eeuo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RUNTIMES_DIR="${PLATFORM_RUNTIMES_DIR:-${ROOT}/platform/runtimes}"

RUNTIME=""
OUT_FILE=""

usage() {
  echo "usage: $0 <runtime> [output.yaml]" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage ;;
    *)
      if [[ -z "${RUNTIME}" ]]; then
        RUNTIME="$1"
      elif [[ -z "${OUT_FILE}" ]]; then
        OUT_FILE="$1"
      else
        usage
      fi
      shift
      ;;
  esac
done

[[ -n "${RUNTIME}" ]] || usage

PROFILE="${RUNTIMES_DIR}/${RUNTIME}.yml"
if [[ ! -f "${PROFILE}" ]]; then
  echo "ERROR: unknown runtime '${RUNTIME}' — add platform/runtimes/${RUNTIME}.yml" >&2
  exit 1
fi

if ! yq -e '.chart | type == "!!map"' "${PROFILE}" >/dev/null 2>&1; then
  echo "ERROR: ${PROFILE} missing required map key 'chart'" >&2
  exit 1
fi

YAML="$(yq -y '.chart' "${PROFILE}" 2>/dev/null || yq '.chart' "${PROFILE}")"
# Header for operators reading the generated file.
YAML="# Generated by scripts/resolve-runtime-values.sh — do not edit by hand.
# runtime: ${RUNTIME}
${YAML}"

if [[ -n "${OUT_FILE}" ]]; then
  printf '%s\n' "${YAML}" > "${OUT_FILE}"
else
  printf '%s\n' "${YAML}"
fi
