#!/usr/bin/env bash
# Resolve a runtime profile into a flat Helm values file for one workload type.
#
# Single source of truth: platform/runtimes/<runtime>.yml
# Merge: chart.defaults ← chart.workloads.<workload>  (deep merge; workload wins)
#
# Usage:
#   ./scripts/resolve-runtime-values.sh <runtime> <workload> [output.yaml]
#
# workload ∈ web | grpc | worker | scheduledJob
#
# Env:
#   PLATFORM_RUNTIMES_DIR  Override the directory of runtime profiles (tests/fixtures).
#
# Prints YAML to stdout when output path is omitted.
set -Eeuo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RUNTIMES_DIR="${PLATFORM_RUNTIMES_DIR:-${ROOT}/platform/runtimes}"

RUNTIME=""
WORKLOAD=""
OUT_FILE=""

usage() {
  echo "usage: $0 <runtime> <workload> [output.yaml]" >&2
  echo "  workload: web | grpc | worker | scheduledJob" >&2
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage ;;
    *)
      if [[ -z "${RUNTIME}" ]]; then
        RUNTIME="$1"
      elif [[ -z "${WORKLOAD}" ]]; then
        WORKLOAD="$1"
      elif [[ -z "${OUT_FILE}" ]]; then
        OUT_FILE="$1"
      else
        usage
      fi
      shift
      ;;
  esac
done

[[ -n "${RUNTIME}" && -n "${WORKLOAD}" ]] || usage

case "${WORKLOAD}" in
  web|grpc|worker|scheduledJob) ;;
  *)
    echo "ERROR: unknown workload '${WORKLOAD}' — expected web|grpc|worker|scheduledJob" >&2
    exit 1
    ;;
esac

PROFILE="${RUNTIMES_DIR}/${RUNTIME}.yml"
if [[ ! -f "${PROFILE}" ]]; then
  echo "ERROR: unknown runtime '${RUNTIME}' — add platform/runtimes/${RUNTIME}.yml" >&2
  exit 1
fi

if ! yq -e '.chart.defaults | type == "!!map"' "${PROFILE}" >/dev/null 2>&1; then
  echo "ERROR: ${PROFILE} missing required map key 'chart.defaults'" >&2
  exit 1
fi

# Deep-merge defaults with optional workloads.<tipo> (absent → {}).
export RESOLVE_WORKLOAD="${WORKLOAD}"
MERGED="$(yq -P '.chart.defaults *d (.chart.workloads[strenv(RESOLVE_WORKLOAD)] // {})' "${PROFILE}")"

YAML="# Generated by scripts/resolve-runtime-values.sh — do not edit by hand.
# runtime: ${RUNTIME}  workload: ${WORKLOAD}
${MERGED}"

if [[ -n "${OUT_FILE}" ]]; then
  printf '%s\n' "${YAML}" > "${OUT_FILE}"
else
  printf '%s\n' "${YAML}"
fi
